name: Release and create Publish PR

on:
  push:
    branches:
      - releases/**

permissions:
  contents: write
  pull-requests: write

jobs:
  check-and-release:
    name: Check and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target
        run: git fetch origin ${{ env.BASE_REF }}
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: âš™ï¸ Check for version plan
        run: npx nx release plan:check --verbose

      - name: ğŸ“ Release new version (skip publish)
        run: npx nx release --skip-publish --verbose

      - name: ğŸ“¤ Create publish pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.head_ref }}
          title: 'Chore: Publish packages'
          commit-message: 'chore: publish package'
          body: |
            Automated publish PR created by Nx Release workflow.
            - Version bumps
            - Updated changelogs
          base: main
